version: "3"

networks:
  react_express_app:
    driver: bridge

services:
  frontend:
    build: .
    container_name: front
    tty: true
    volumes:
      - ../frontend:/frontend
    working_dir: "/frontend"
    ports:
      - 3001:3000
    networks:
      - react_express_app
  backend:  # Express用のコンテナ
    build: .
    container_name: back
    tty: true
    volumes:
      - ../backend:/backend
    working_dir: "/backend"
    ports:
      - 3002:3000
    depends_on:
      - db
    links:
      - db
    networks:
      - react_express_app
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: react_express_db
    ports:
      - 3306:3306
    volumes:
      - my_volume:/var/lib/mysql
    networks:
      - react_express_app

volumes: 
  my_volume: